name: hotlink-test
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - earthaccess
  - ephem
  - scipy
  - scikit-image
  - Pillow
  - pyresample
  - tensorflow<=2.15
  - matplotlib
  - utm
  - satpy['modis_1b']
  - satpy['viirs_1b']